name: Staging

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: build and push
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Current Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gitbuilder-landing
          tags: ${{ steps.package-version.outputs.current-version}}
